#!/usr/bin/env python
"""This is a class and a script to api to PowerDnsAdmin."""

# pylint: disable=E0401
from admin_api.clientapi import Clientapi


CLIAPI = Clientapi()
print('######## performing add')
# pylint: disable=C0103
dictof = {
    'admin-internal.spotx.tg1.vips.den01.pop': 'admindash.spotx.den01.pop',
    'spotmarket-mutate.spotx.den01.pop': 'supply-mutate.spotx.den01.pop',
    'spotmarket-read.spotx.den01.pop': 'supply-read.spotx.den01.pop',
    'sw1.den01.pop': 'sw1.spotx.den01.pop',
    'sw2.den01.pop': 'sw2.spotx.den01.pop',
    'syncconf.den01.pop': 'syncconf.spotx.den01.pop',
    'tableau.spotx.den01.pop': 'tableau001.den01.pop',
    'temptrax.den01.pop': 'temptrax.spotx.den01.pop',
    'vault.den01.pop': 'vault.spotx.den01.pop',
    'vpn001.den01.pop': 'vpn.spotx.den01.pop'}

dictof['fred.den01.pop.'] = 'audiencequery004rac.spotx.den01.pop.'

dictof = {
    'audiencequery003rac.spotx.iad02.pop.': '192.168.136.82'}
dictof = {
    'audiencesync002.spotx.ams01.pop.': '192.168.144.120'}
dictof = {
    'doubleverify002.spotx.ams01.pop.': '192.168.144.153'}

for name in dictof:
    content = dictof[name]
    #CLIAPI.perform_delete(name=name, rectype='A')
    #CLIAPI.perform_add(name=name, content=content, rectype='CNAME')
    #CLIAPI.perform_delete(name=name, rectype='CNAME')
    CLIAPI.perform_add(name=name, content=content, rectype='A')
