#!/usr/bin/env python
"""This is a class and a script to api to PowerDnsAdmin."""

# pylint: disable=E0401
from admin_api.clientapi import Clientapi


CLIAPI = Clientapi()
print('######## performing add')
# pylint: disable=C0103
dictof = {}
dictof['fred.den01.pop.'] = '192.168.45.255'
for name in dictof:
    ipaddr = dictof[name]
    CLIAPI.perform_add(name=name, ipaddr=ipaddr)
