#!/bin/bash
#curl -H 'X-API-Key: o1eir9ahPhu7teighei2zoh,shaey' http://dnstest2:8081/api/v1/servers/localhost/zones | jq 
#curl -H 'X-API-Key: o1eir9ahPhu7teighei2zoh,shaey' http://dnstest2:8081/api/v1/servers/localhost/zones/spotx.tv | jq

#url="http://localhost:9393/apitest"
#action="POST"

url="http://dnstest2:8081/api/v1/servers/localhost/zones/spotx.tv."
action="PATCH"

curl -X ${action} --data '{"rrsets": [{
  "name": "fredd.spotx.tv.",
  "type": "A",
  "ttl": 86400,
  "changetype": "REPLACE",
  "records": [ {
    "content": "192.168.2.28",
    "disabled": false
  }]
}]}' \
  -H 'X-API-Key: o1eir9ahPhu7teighei2zoh,shaey' \
  ${url} | jq


