#!/bin/bash
#curl -H 'X-API-Key: o1eir9ahPhu7teighei2zoh,shaey' http://dnstest2:8081/api/v1/servers/localhost/zones | jq 
#curl -H 'X-API-Key: o1eir9ahPhu7teighei2zoh,shaey' http://dnstest2:8081/api/v1/servers/localhost/zones/spotx.tv | jq

#url="http://localhost:9393/apitest"
#action="POST"

zone="pop"
url="http://dnstest2:8081/api/v1/servers/localhost/zones/${zone}."
action="POST"
action="PATCH"

#curl \
curl -X ${action} \
 --data @/home/dbartley/projects/PowerDNS-Admin_api/data \
 -H 'X-API-Key: o1eir9ahPhu7teighei2zoh,shaey' \
  ${url} \
  | jq


