#!/usr/bin/env python
"""This is a class and a script to api to PowerDnsAdmin."""

# pylint: disable=E0401
from admin_api.clientapi import Clientapi
import sys


CLIAPI = Clientapi()
print('######## performing add')
# pylint: disable=C0103
#1 but wrong vcs52u002.sin01.pop 12.96.168.192.in-addr.arpa vcs44u002.sin01.pop
dictof = {

   '1.40.168.192.in-addr.arpa': 'gw.den01.pop',
    '233.47.168.192.in-addr.arpa': 'bc8slot13.spotx.den01.pop',
    '99.47.168.192.in-addr.arpa': 'bc020slot6.spotx.den01.pop'}

for revname in dictof:
    hostname = dictof[revname]
    print "Attempting chage revname %s to be a PTR record pointing to %s " % (revname, hostname)
    CLIAPI.fixrev(hostname=hostname, revname=revname)
    #sys.exit()
