#!/usr/bin/env python
"""A script to clean up the powerdns data."""

# import os
# import sys
# import re
# import ipaddress
# from pprint import pprint  # , pformat

# pylint: disable=E0401,R0903
# pylint: disable=invalid-name

# from sqlalchemy import func, desc
# from admin_api.clientapi import Clientapi
from admin_api.pdnsmodels import Domains, Records, session

checkdomain = 'pop'
newdomlist = []
newdomlist.append('den01.pop')
newdomlist.append('sin01.pop')
newdomlist.append('ams01.pop')
newdomlist.append('iad02.pop')


def domqry(name=None, dofirst=False):
    """get a model for a domain."""
    qry = session.query(Domains)
    if name:
        qry = qry.filter(Domains.name == name)
    if dofirst:
        qry = qry.first()
    return qry


def record_query(domid, type_=None, namelike=None, doall=False, dofirst=False):
    """Build query on records table."""
    nsq = session.query(Records)\
                 .filter(Records.domain_id == domid)
    if type_:
        nsq = nsq.filter(Records.type == type_)
    if namelike:
        nsq = nsq.filter(Records.name.like("%%.%s" % (newdom.name)))
    if dofirst:
        nsq = nsq.first()
    elif doall:
        nsq = nsq.all()
    return nsq


def dupnsrecs(qry, newdomid):
    """Duplicate the NS records of pop to new domain."""
    for nsrec in qry:
        print("duplicating %s for %s" % (nsrec, newdomid))
        newnsrec = nsrec.duplicate()
        newnsrec.domain_id = newdomid
        session.add(newnsrec)
    session.commit()


def dupsoarec(mdl, newdomid, newdomain_name):
    """Duplicate the SOA record from pop to new domain."""
    print("duplicating %s for %s, with name %s" % (mdl, newdomid, newdomain_name))
    newsoarec = mdl.duplicate()
    newsoarec.domain_id = newdomid
    newsoarec.name = newdomain_name
    print("newsoarec content %s" % (newsoarec.content))
    print(newsoarec)
    session.add(newsoarec)
    session.commit()


if __name__ == '__main__':
    qry = domqry()
    for item in qry:
        # print("domain is %s" % (item))
        print "pdnsutil set-meta %s SOA-EDIT INCEPTION" % (item.name)
        print "pdnsutil set-meta %s SOA-EDIT-API DEFAULT" % (item.name)
