#!/bin/bash


function dodig {
    dostop=$1
    dighost="dnstest2"
    dighost="dnsmanager.den01.pop"
	cmd="dig -p5300 @${dighost} -x ${ipaddr}"
    echo ${cmd}
    ${cmd}
	cmd="dig -p5300 @${dighost} ${host}"
    echo ${cmd}
    ${cmd}
    echo "<cr> to continue"
    if [ -z ${dostop} ] ; then
        read dum
    fi
}

#host="audiencedb002rac.spotx.iad02.pop."
#ipaddr="192.168.136.245"
host="be7rac.spotx.den01.pop."
ipaddr="192.168.41.252"

echo "running on host = ${host} and ipaddr = ${ipaddr}"
dodig

echo changing host ${host} to ipaddr ${ipaddr}
./addhost ${host} ${ipaddr}

dodig asdf

#dig @${dighost} -x ${ipaddr}
#dig @${dighost} ${host}
